import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'th';

const translations = {
    en: {
        // General
        'status': 'Status',
        'actions': 'Actions',
        'cancel': 'Cancel',
        'create': 'Create',
        'delete': 'Delete',
        'update': 'Update',
        'monitor': 'Monitor',
        'deploy': 'Deploy',
        'edit_exam': 'Edit Form',
        'achievement': 'Score',
        'submitted': 'Submitted',
        'yes': 'Yes',
        'no': 'No',
        'dismiss': 'Dismiss',
        'success': 'Success',
        'error': 'Error',
        'warning': 'Warning',
        'student': 'Student',
        'lecturer': 'Lecturer',
        'role_admin': 'Administrator',
        'section': 'Section',

        // Navbar
        'dashboard': 'Dashboard',
        'new_exam': 'New Form',
        'admin': 'Admin',
        'logout': 'Logout',

        // Dashboard
        'academic_overview': 'Academic Overview',
        'create_exam': 'Create Form',
        'collections': 'Semester',
        'all_examinations': 'All Forms/Assessments',
        'ungrouped': 'Ungrouped',
        'move_to_collection': 'Move to Collection',
        'delete_collection': 'Delete Collection',
        'create_new_collection': 'Create New Collection',
        'add_exams_to_collection': 'Add Forms to this Collection',

        'edit_content': 'Edit Content',
        'duplicate_exam': 'Duplicate Form',
        'export_results': 'Export Results',
        'export_exam_data': 'Export Form Data',
        'scan_to_access_exam': 'Share QR Code',
        'real_time_monitor': 'Real-time Monitor',
        'reset_results': 'Reset Results',

        'start_now': 'Start Now',
        'view_result': 'View Result',
        'start': 'Start',
        'closed': 'Closed',
        'force_stop': 'Force Stop',
        'stop': 'Stop',
        'manual_start': 'Manual Start',

        'assign_exam': 'Assign Form',
        'select_destination': 'Select Destination',
        'ungrouped_sessions': 'Ungrouped Sessions',
        'all_sessions': 'All Sessions',
        'no_exams_found': 'No forms found in this group.',
        'no_records_found': 'No matching records detected',
        'search': 'Search...',
        'back_to_dashboard': 'Back to Dashboard',

        // Alerts
        'delete_group_confirm': 'Delete this group?',
        'delete_group_text': 'Forms will be moved to "Ungrouped".',
        'group_deleted': 'The group has been deleted.',
        'exam_moved': 'Form has been moved successfully.',
        'force_stop_confirm': 'Force Stop Assessment?',
        'force_stop_text': 'Late submissions are allowed. Stopping this will prevent any further submissions.',
        'reset_confirm': 'CRITICAL ACTION',
        'reset_text': 'This will PERMANENTLY delete all student submissions and results for this form.',
        'duplicate_confirm': 'Duplicate this form?',
        'duplicate_text': 'You will create a copy of this form.',
        'exam_duplicated': 'The form has been duplicated.',
        'submit_exam_confirm': 'Submit Form?',
        'submit_exam_text': 'Are you sure you want to finish your assessment? This action cannot be undone.',
        'live_session': 'Live',
        'finish': 'Submit',
        'finalize_submission': 'Finalize Submission',
        'security_alert_title': 'Security Alert',
        'security_alert_away': 'Window focus lost. Please return to the form page immediately.',
        'security_alert_return': 'Tap anywhere to dismiss',
        'answered_of': 'answered of',
        'assessment': 'Assessment',
        'overdue': 'Overdue',
        'waiting_for_host': 'Waiting for Host',
        'upcoming_assessment': 'Upcoming Assessment',
        'session_begin_shortly': 'The session will begin shortly.',
        'starts_at': 'Starts at',
        'system_synchronized': 'System synchronized.',
        'connected_stay_on_page': 'Connected. Please stay on this page.',
        'starts_in': 'Starts in',
        // Collection
        'group_name_placeholder': 'Group Name...',
        'new': 'New',

        // Create Exam
        'back_to_overview': 'Back to Overview',
        'general_questions': 'General Questions',
        'ungrouped_questions': 'Ungrouped Questions',
        'questions': 'Questions',
        'new_section': 'New Section',
        'untitled_exam': 'Untitled Form',
        'course_description': 'Description',
        'duration_minutes': 'Duration (minutes)',
        'start_configuration': 'Start Configuration',
        'scheduled': 'Scheduled',
        'manual': 'Manual',
        'collection_group': 'Semester (Group)',
        'no_collection': 'No Semester',
        'collection_help': 'Categorize this form for easier management in your dashboard',
        'public_exam': 'Public Form',
        'public_exam_help': 'Available to all registered students',
        'show_in_dashboard': 'Show in Student Dashboard',
        'show_in_dashboard_help': 'Display this form on all student dashboards without QR code',

        // Backup
        'backups': 'Backups',
        'backup_management': 'Backup Management',
        'backup_exam': 'Backup',
        'backup_created': 'Backup created successfully',
        'backup_deleted': 'Backup has been deleted',
        'backup_download': 'Download',
        'backup_type': 'Type',
        'backup_auto': 'Auto',
        'backup_manual': 'Manual',
        'backup_date': 'Backup Date',
        'backup_submissions': 'Submissions',
        'backup_questions': 'Questions',
        'no_backups_found': 'No backups found',
        'delete_backup_confirm': 'Delete this backup?',
        'delete_backup_text': 'This will permanently remove this backup data.',
        'create_backup': 'Create Backup',
        'create_backup_confirm': 'Backup this form?',
        'create_backup_text': 'This will create a snapshot of all form data including submissions and results.',

        // Login
        'permitted_emails': 'Permitted Emails',
        'paste_emails': 'Paste student emails or patterns (e.g., 48214*) separated by spaces, commas or new lines...',
        'valid_emails_detected': 'valid emails detected',
        'shuffle_questions': 'Shuffle Questions',
        'shuffle_questions_help': 'Randomize question order',
        'shuffle_options': 'Shuffle Options',
        'shuffle_options_help': 'Randomize answer choices',
        'instant_feedback': 'Instant Feedback',
        'instant_feedback_help': 'Allow students to see their score after submission',
        'late_submissions': 'Late Submissions',
        'late_submissions_help': 'Allow students to submit after time ends',
        'live_monitoring': 'Live Video Monitoring',
        'live_monitoring_help': 'Enable real-time WebRTC proctoring during assessment',
        'move_section_up': 'Move Section Up',
        'move_section_down': 'Move Section Down',
        'delete_section': 'Delete Section',
        'section_title': 'Section Title',
        'section_description_optional': 'Section description (optional)',
        'type_question': 'Type your question here...',
        'short_answer': 'Short Answer',
        'paragraph': 'Paragraph',
        'multiple_choice': 'Multiple Choice',
        'checkboxes': 'Checkboxes',
        'uploading': 'Uploading...',
        'add_image': 'Add Image',
        'correct_answer': 'Correct Answer',
        'option': 'Option',
        'add_option': 'Add Option',
        'short_answer_placeholder': 'Students will type their answer here...',
        'required': 'Required',
        'move_to': 'Move to:',
        'duplicate': 'Duplicate',
        'add_question_to': 'Add Question to',
        'add_new_section': 'Add New Section',
        'update_exam_blueprint': 'Update',
        'deploy_exam_blueprint': 'Deploy',
        'exam_updated_success': 'Form updated successfully!',
        'exam_created_success': 'Form created successfully!',
        'error_updating_exam': 'Error updating form',
        'error_creating_exam': 'Error creating form',
        'failed_upload_image': 'Failed to upload image',
        'error_loading_data': 'Error loading form data',
        'imported_questions': 'Imported Questions',
        'bulk_import_questions': 'Bulk Import Questions',
        'import_from_csv_excel': 'Import from CSV / Excel',
        'download_template': 'Download CSV Template',
        'apply_wildcards': 'Apply * to all patterns',
        'theme_configuration': 'Appearance',
        'primary_color': 'Primary Accent',
        'background_color': 'Background',
        'text_color': 'Text Color',
        'presets': 'Presets',
        'theme_default': 'Standard Blue',
        'theme_midnight': 'Midnight Dark',
        'theme_eco': 'Emerald Green',
        'theme_sunset': 'Amber Sunset',
        'theme_rose': 'Ruby Rose',
        'theme_lavender': 'Soft Lavender',
        'theme_slate': 'Professional Slate',
        'theme_teal': 'Ocean Teal',
        'theme_indigo': 'Deep Indigo',
        'theme_peach': 'Warm Peach',
        'bloom_taxonomy_levels': "Bloom's Taxonomy Levels",
        'simplicity_evaluation_consistency': 'Simplicity in evaluation. Consistency in performance.',
        'simplicity': 'Simplicity',
        'secured': 'Secured',
        'academic': 'Academic',
        'total': 'Total',
        'focused': 'Focused',
        'away': 'Away',
        'completed': 'Completed',
        'active': 'Active',
        'live': 'Live',
        'security_activity': 'Security Activity',
        'max_score': 'Max Score',
        'min_score': 'Min Score',
        'avg_score': 'Avg Score',

        // Login
        'welcome_to': 'Welcome to MeritSpace',
        'secure_academic_platform': 'intelligent assessment platform',
        'login_failed': 'Login Failed',
        'auth_failed': 'Failed to authenticate with server.',
        'google_auth_failed': 'Google authentication failed. Please try again.',
        'encrypted': 'Encrypted',
        'secure': 'Secure',
        'auth_powered_by': 'Authentication powered by Google.',
        'institutional_accounts': 'Only institutional accounts are permitted.',
        'protected_by': 'Protected by enterprise-grade security standards',
    },
    th: {
        // General
        'status': 'สถานะ',
        'actions': 'การดำเนินการ',
        'cancel': 'ยกเลิก',
        'create': 'สร้าง',
        'delete': 'ลบ',
        'update': 'อัปเดต',
        'monitor': 'ติดตาม',
        'deploy': 'เผยแพร่',
        'edit_exam': 'แก้ไขแบบฟอร์ม',
        'achievement': 'คะแนน',
        'submitted': 'ส่งแล้ว',
        'yes': 'ใช่',
        'no': 'ไม่',
        'dismiss': 'ปิด',
        'success': 'สำเร็จ',
        'error': 'ข้อผิดพลาด',
        'warning': 'คำเตือน',
        'student': 'นักเรียน',
        'lecturer': 'อาจารย์',
        'role_admin': 'ผู้ดูแลระบบ',
        'section': 'ส่วน',

        // Navbar
        'dashboard': 'แดชบอร์ด',
        'new_exam': 'สร้างแบบฟอร์มใหม่',
        'admin': 'ผู้ดูแลระบบ',
        'logout': 'ออกจากระบบ',

        // Dashboard
        'academic_overview': 'ภาพรวมเทอม',
        'create_exam': 'สร้างแบบฟอร์ม',
        'collections': 'เทอม',
        'all_examinations': 'แบบฟอร์ม/การประเมินทั้งหมด',
        'ungrouped': 'ไม่มีกลุ่ม',
        'move_to_collection': 'ย้ายไปยังเทอม',
        'delete_collection': 'ลบเทอม',
        'create_new_collection': 'สร้างเทอมใหม่',
        'add_exams_to_collection': 'เพิ่มแบบฟอร์มในเทอมนี้',

        'edit_content': 'แก้ไขเนื้อหา',
        'duplicate_exam': 'ทำสำเนาแบบฟอร์ม',
        'export_results': 'ส่งออกผลลัพธ์',
        'export_exam_data': 'ส่งออกข้อมูลแบบฟอร์ม',
        'scan_to_access_exam': 'แชร์ QR Code',
        'real_time_monitor': 'ติดตามแบบเรียลไทม์',
        'reset_results': 'รีเซ็ตผลลัพธ์',

        'start_now': 'เริ่มทันที',
        'view_result': 'ดูผลลัพธ์',
        'start': 'เริ่มทำ',
        'closed': 'ปิดแล้ว',
        'force_stop': 'บังคับหยุด',
        'stop': 'หยุด',
        'manual_start': 'เริ่มด้วยตนเอง',

        'assign_exam': 'มอบหมายแบบฟอร์ม',
        'select_destination': 'เลือกปลายทาง',
        'ungrouped_sessions': 'เซสชันที่ไม่มีกลุ่ม',
        'all_sessions': 'เซสชันทั้งหมด',
        'no_exams_found': 'ไม่พบแบบฟอร์มในกลุ่มนี้',
        'no_records_found': 'ไม่พบข้อมูลที่ตรงกัน',
        'search': 'ค้นหา...',
        'back_to_dashboard': 'กลับสู่แดชบอร์ด',

        // Alerts
        'delete_group_confirm': 'ลบกลุ่มนี้หรือไม่?',
        'delete_group_text': 'แบบฟอร์มจะถูกย้ายไปที่ "ไม่มีกลุ่ม"',
        'group_deleted': 'ลบกลุ่มเรียบร้อยแล้ว',
        'exam_moved': 'ย้ายแบบฟอร์มเรียบร้อยแล้ว',
        'force_stop_confirm': 'บังคับหยุดการประเมิน?',
        'force_stop_text': 'อนุญาตให้ส่งช้าได้ การหยุดนี้จะป้องกันการส่งข้อมูลเพิ่มเติมทั้งหมด',
        'reset_confirm': 'การดำเนินการสำคัญ',
        'reset_text': 'การดำเนินการนี้จะลบการส่งข้อมูลและผลลัพธ์ทั้งหมดอย่างถาวรสำหรับแบบฟอร์มนี้',
        'duplicate_confirm': 'ทำสำเนาแบบฟอร์มนี้?',
        'duplicate_text': 'คุณจะสร้างสำเนาของแบบฟอร์มนี้',
        'exam_duplicated': 'ทำสำเนาแบบฟอร์มเรียบร้อยแล้ว',
        'submit_exam_confirm': 'ยืนยันการส่งแบบฟอร์ม?',
        'submit_exam_text': 'คุณแน่ใจหรือไม่ว่าต้องการจบการประเมิน? การดำเนินการนี้ไม่สามารถย้อนกลับได้',
        'live_session': 'Live',
        'finish': 'ส่งข้อมูล',
        'finalize_submission': 'ยืนยันการส่งข้อมูล',
        'security_alert_title': 'การแจ้งเตือนความปลอดภัย',
        'security_alert_away': 'ตรวจพบการออกจากหน้าจอ กรุณากลับเข้าสู่หน้าจอทันทีเพื่อดำเนินการต่อ',
        'security_alert_return': 'แตะเพื่อปิดการแจ้งเตือน',
        'answered_of': 'ข้อที่ตอบแล้ว จากทั้งหมด',
        'assessment': 'การประเมินผล',
        'overdue': 'เลยกำหนดเวลา',
        'waiting_for_host': 'รอผู้คุมสอบเริ่มต้น',
        'upcoming_assessment': 'การประเมินที่กำลังจะมาถึง',
        'session_begin_shortly': 'เซสชันจะเริ่มในเร็วๆ นี้',
        'starts_at': 'เริ่มเวลา',
        'system_synchronized': 'ระบบซิงค์เสร็จสิ้น',
        'connected_stay_on_page': 'เชื่อมต่อแล้ว กรุณาอยู่ในหน้านี้',
        'starts_in': 'จะเริ่มในอีก',
        // Collection
        'group_name_placeholder': 'ชื่อกลุ่ม...',
        'new': 'ใหม่',

        // Create Exam
        'back_to_overview': 'กลับสู่ภาพรวม',
        'general_questions': 'คำถามทั่วไป',
        'ungrouped_questions': 'คำถามที่ไม่มีกลุ่ม',
        'questions': 'คำถาม',
        'new_section': 'ส่วนใหม่',
        'untitled_exam': 'แบบฟอร์มไม่มีชื่อ',
        'course_description': 'รายละเอียด',
        'duration_minutes': 'ระยะเวลา (นาที)',
        'start_configuration': 'การตั้งค่าการเริ่ม',
        'scheduled': 'ตามกำหนดการ',
        'manual': 'ด้วยตนเอง',
        'collection_group': 'เทอม (กลุ่ม)',
        'no_collection': 'ไม่มีเทอม',
        'collection_help': 'จัดหมวดหมู่แบบฟอร์มนี้เพื่อการจัดการที่ง่ายขึ้นในแดชบอร์ดของคุณ',
        'public_exam': 'แบบฟอร์มสาธารณะ',
        'public_exam_help': 'เปิดให้สำหรับผู้ใช้ที่ลงทะเบียนทั้งหมด',
        'show_in_dashboard': 'แสดงในแดชบอร์ด',
        'show_in_dashboard_help': 'แสดงแบบฟอร์มนี้ในแดชบอร์ดทุกคนโดยไม่ต้องแชร์ QR โค้ด',

        // Backup
        'backups': 'สำรองข้อมูล',
        'backup_management': 'จัดการข้อมูลสำรอง',
        'backup_exam': 'สำรอง',
        'backup_created': 'สร้างข้อมูลสำรองเรียบร้อยแล้ว',
        'backup_deleted': 'ข้อมูลสำรองถูกลบแล้ว',
        'backup_download': 'ดาวน์โหลด',
        'backup_type': 'ประเภท',
        'backup_auto': 'อัตโนมัติ',
        'backup_manual': 'ด้วยตนเอง',
        'backup_date': 'วันที่สำรอง',
        'backup_submissions': 'การส่ง',
        'backup_questions': 'คำถาม',
        'no_backups_found': 'ไม่พบข้อมูลสำรอง',
        'delete_backup_confirm': 'ลบข้อมูลสำรองนี้?',
        'delete_backup_text': 'การดำเนินการนี้จะลบข้อมูลสำรองนี้อย่างถาวร',
        'create_backup': 'สร้างข้อมูลสำรอง',
        'create_backup_confirm': 'สำรองแบบฟอร์มนี้?',
        'create_backup_text': 'สิ่งนี้จะสร้างสำเนาข้อมูลแบบฟอร์มทั้งหมดรวมถึงการส่งและผลลัพธ์',

        // Login
        'permitted_emails': 'อีเมลที่ได้รับอนุญาต',
        'paste_emails': 'วางอีเมลผู้ใช้หรือรูปแบบ (เช่น 48214*) โดยคั่นด้วยช่องว่าง จุลภาค หรือบรรทัดใหม่...',
        'valid_emails_detected': 'อีเมลที่ถูกต้องที่ตรวจพบ',
        'shuffle_questions': 'สลับข้อ',
        'shuffle_questions_help': 'สุ่มลำดับข้อ',
        'shuffle_options': 'สลับตัวเลือก',
        'shuffle_options_help': 'สุ่มตัวเลือกคำตอบ',
        'instant_feedback': 'ผลลัพธ์ทันที',
        'instant_feedback_help': 'อนุญาตให้ดูคะแนนหลังจากส่งข้อมูล',
        'late_submissions': 'การส่งล่าช้า',
        'late_submissions_help': 'อนุญาตให้ส่งพ้นกำหนดเวลาได้',
        'live_monitoring': 'การคุมสอบออนไลน์ (Live)',
        'live_monitoring_help': 'เปิดใช้งานการติดตามผ่านกล้องเว็บแคมแบบเรียลไทม์ (WebRTC)',
        'move_section_up': 'เลื่อนส่วนขึ้น',
        'move_section_down': 'เลื่อนส่วนลง',
        'delete_section': 'ลบส่วน',
        'section_title': 'ชื่อส่วน',
        'section_description_optional': 'คำอธิบายส่วน (ไม่บังคับ)',
        'type_question': 'พิมพ์คำถามของคุณที่นี่...',
        'short_answer': 'คำตอบสั้น',
        'paragraph': 'ย่อหน้า/บรรยาย',
        'multiple_choice': 'ปรนัย',
        'checkboxes': 'ช่องทำเครื่องหมาย',
        'uploading': 'กำลังอัปโหลด...',
        'add_image': 'เพิ่มรูปภาพ',
        'correct_answer': 'คำตอบที่ถูกต้อง',
        'option': 'ตัวเลือก',
        'add_option': 'เพิ่มตัวเลือก',
        'short_answer_placeholder': 'ระบุคำตอบที่นี่...',
        'required': 'จำเป็น',
        'move_to': 'ย้ายไปที่:',
        'duplicate': 'ทำสำเนา',
        'add_question_to': 'เพิ่มคำถามไปยัง',
        'add_new_section': 'เพิ่มส่วนใหม่',
        'update_exam_blueprint': 'อัปเดตแบบฟอร์ม',
        'deploy_exam_blueprint': 'เผยแพร่แบบฟอร์ม',
        'exam_updated_success': 'อัปเดตแบบฟอร์มสำเร็จ!',
        'exam_created_success': 'สร้างแบบฟอร์มสำเร็จ!',
        'error_updating_exam': 'ข้อผิดพลาดในการอัปเดตแบบฟอร์ม',
        'error_creating_exam': 'ข้อผิดพลาดในการสร้างแบบฟอร์ม',
        'failed_upload_image': 'อัปโหลดรูปภาพไม่สำเร็จ',
        'error_loading_data': 'ข้อผิดพลาดในการโหลดข้อมูลแบบฟอร์ม',
        'imported_questions': 'คำถามที่นำเข้า',
        'bulk_import_questions': 'นำเข้าคำถามแบบกลุ่ม',
        'import_from_csv_excel': 'นำเข้าจาก CSV / Excel',
        'download_template': 'ดาวน์โหลดไฟล์ตัวอย่าง',
        'apply_wildcards': 'ใช้เครื่องหมาย * ให้ทุกรายการ',
        'theme_configuration': 'รูปลักษณ์',
        'primary_color': 'สีเน้นหลัก',
        'background_color': 'สีพื้นหลัง',
        'text_color': 'สีตัวอักษร',
        'presets': 'ธีมสำเร็จรูป',
        'theme_default': 'ฟ้ามาตรฐาน',
        'theme_midnight': 'มิดไนท์ดาร์ก',
        'theme_eco': 'เขียวธรรมชาติ',
        'theme_sunset': 'ส้มอำพัน',
        'theme_rose': 'ชมพูทับทิม',
        'theme_lavender': 'ซอฟต์ลาเวนเดอร์',
        'theme_slate': 'สเลททางการ',
        'theme_teal': 'โอเชียนทีล',
        'theme_indigo': 'ดีพอินดิโก้',
        'theme_peach': 'วอร์มพีช',
        'bloom_taxonomy_levels': 'ระดับพุทธิพิสัย (Bloom\'s Taxonomy)',
        'simplicity_evaluation_consistency': 'ความเรียบง่ายในการประเมิน ความสม่ำเสมอในประสิทธิภาพ',
        'simplicity': 'เรียบง่าย',
        'secured': 'ปลอดภัย',
        'academic': 'วิชาการ',
        'total': 'ทั้งหมด',
        'focused': 'โฟกัส',
        'away': 'ออกไป',
        'completed': 'เสร็จสิ้น',
        'active': 'กำลังออนไลน์',
        'live': 'ไลฟ์',
        'security_activity': 'กิจกรรมความปลอดภัย',
        'max_score': 'คะแนนสูงสุด',
        'min_score': 'คะแนนต่ำสุด',
        'avg_score': 'คะแนนเฉลี่ย',

        // Login
        'welcome_to': 'ยินดีต้อนรับสู่ MeritSpace',
        'secure_academic_platform': 'แพลตฟอร์มการประเมินอัจฉริยะ',
        'login_failed': 'การเข้าสู่ระบบล้มเหลว',
        'auth_failed': 'ไม่สามารถยืนยันตัวตนกับเซิร์ฟเวอร์ได้',
        'google_auth_failed': 'การยืนยันตัวตน Google ล้มเหลว โปรดลองอีกครั้ง',
        'encrypted': 'เข้ารหัส',
        'secure': 'ปลอดภัย',
        'auth_powered_by': 'การยืนยันตัวตนโดย Google',
        'institutional_accounts': 'อนุญาตเฉพาะบัญชีสถาบันเท่านั้น',
        'protected_by': 'ได้รับการปกป้องด้วยมาตรฐานความปลอดภัยระดับองค์กร',
    }
};

type LanguageContextType = {
    language: Language;
    toggleLanguage: () => void;
    t: (key: keyof typeof translations['en']) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguage] = useState<Language>(() => {
        const saved = localStorage.getItem('language');
        return (saved === 'en' || saved === 'th') ? saved : 'en';
    });

    useEffect(() => {
        localStorage.setItem('language', language);
    }, [language]);

    const toggleLanguage = () => {
        setLanguage(prev => prev === 'en' ? 'th' : 'en');
    };

    const t = (key: keyof typeof translations['en']) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
